using System.ComponentModel.DataAnnotations;

namespace EventManagementPortal.Models;

public class Event
{
    public int Id { get; set; } //Primary key is automatically generated by the database

    //Event title
    [Required(ErrorMessage = "Title is required")]
    [StringLength(200, ErrorMessage = "Title cannot exceed 200 characters")]
    public string Title { get; set; } = string.Empty;

    //Event Description
    [Required(ErrorMessage = "Event description is required")]
    [StringLength(2000, ErrorMessage = "Description cannot exceed 2000 characters")]
    public string Description { get; set; } = string.Empty;

    //Event Location
    [Required(ErrorMessage = "Event location is required")]
    [StringLength(250, ErrorMessage = "Location cannot exceed 250 characters")]
    public string Location { get; set; } = string.Empty;

    //Event Date
    [Required(ErrorMessage = "Event date is required")]
    [Display(Name = "Event Date")]
    public DateTime EventDate { get; set; }


    [Required]
    public string CreatedByUserId { get; set; } = string.Empty; //Foreign Key (ID of the user who created the event)

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow; //When the event record was created in the DB

    public ApplicationUser CreatedBy { get; set; } = null!; //Allows us to access the event creators details

    public ICollection<Guest> Guests { get; set; } = new List<Guest>(); //Guests registered for this event

}